### ISSUE TITLE
NYSE section on the Header section to hide/display based on the Langauage

### ISSUE THREAD

**Issue by MuruliThimmaiah** [trupti-dhall/Harman#14]
Make NYSE section on the Header section to hide/display based on the Langauage

**Comment by trupti-dhall** [comment]
Made NYSE block dependent  on language

**Comment by trupti-dhall** [comment]
Provided option to make it language dependent

**Comment by trupti-dhall** [comment]
Review it and make the description proper

**Comment by debasis123nandi** [comment]
NYSE is in English and not in China
