### ISSUE TITLE
Highlighted part is not showing in iphone 5

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#15]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123 or as viewer
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/solutions
Step 4 : In device , Iphone
Step 5 : Highlighted part is not showing in iphone 5
Step 6 : Screenshot attached
![image](https://cloud.githubusercontent.com/assets/23308564/20087732/25efaf8e-a5a1-11e6-9394-00ebc2675bc9.png)
![image](https://cloud.githubusercontent.com/assets/23308564/20087742/3179cf10-a5a1-11e6-844b-fa8ee8dfb34d.png)

**Comment by trupti-dhall** [comment]
loading issue

**Comment by debasis123nandi** [comment]
Its showing fine now 
![image](https://cloud.githubusercontent.com/assets/23308564/20587146/c60f0f6e-b230-11e6-9217-e1822052ed2f.png)
