### ISSUE TITLE
 In Iphone background of read more is white

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#16]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com
Step 4 : In device , I phone
Step 5 : It is observed that there is no background colour of tooltip text as compared with the site in PC
Step 6: screenshots
![image](https://cloud.githubusercontent.com/assets/23308564/20336839/4b18fdf8-abf3-11e6-851a-759c19985121.png)

**Comment by arpita123das** [comment]
Issue is resolved
URL: http://wipro48ocphrfau.devcloud.acquia-sites.com
![11-9-2016](https://cloud.githubusercontent.com/assets/23329067/20138916/40f3886a-a6a9-11e6-8a17-2e0c968ff8f0.PNG)

**Comment by debasis123nandi** [comment]
Its working fine
