### ISSUE TITLE
Overlapping text 

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#17]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: https://wipro48ocphrfau.devcloud.acquia-sites.com/about-us
Step 4 : In device ,Iphone
step 5 : It is observed that text is getting overlapped as shown below, highlighted 
step 6 :; screenshots
![image](https://cloud.githubusercontent.com/assets/23308564/20336915/be1870a4-abf3-11e6-9560-39d255ec2386.png)

**Comment by arpita123das** [comment]
Issue is resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/about-us
![about-us](https://cloud.githubusercontent.com/assets/23329067/20138272/78625334-a6a5-11e6-8bf3-a127f8d6ce82.PNG)

**Comment by debasis123nandi** [comment]
Its working fine
