### ISSUE TITLE
Hamburger icon is not getting minimized

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#18]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com
Step 4 : In device ,Iphone
Step 5 : Click the hamburger icon on the header
step 6 : It is observed that on clicking the hamburger icon a dropdown menu list appears.
Step 7: Click the Hamburger icon
Step 8 : It is observed that the dropdown list doesnot get minimised
Step 9: Click anywhere on the screen, it is observed that dropdown list doesnot get minimised 
Step 10 :  Screenshots
![image](https://cloud.githubusercontent.com/assets/23308564/20337023/73d49058-abf4-11e6-893b-3bbbb059afdc.png)

**Comment by arpita123das** [comment]
Issue is not replicating from my end,hence closing this issue

**Comment by arpita123das** [comment]
Issue resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/
