### ISSUE TITLE
Text is overlapping with images

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#19]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/recognition
Step 4 : In device , Iphone
Step 5 : It is observed that the image and text is getting overlapping as shown highlighted 
Step 6 : screenshots
![image](https://cloud.githubusercontent.com/assets/23308564/20337321/61780744-abf6-11e6-8934-7ba996c32194.png)

**Comment by arpita123das** [comment]
Issue is resolved.
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/recognition
![recognition](https://cloud.githubusercontent.com/assets/23329067/20137402/381d2894-a6a0-11e6-84b5-b2248d45d70c.PNG)

**Comment by debasis123nandi** [comment]
Its working fine
