### ISSUE TITLE
Create a Template for News

### ISSUE THREAD

**Issue by MuruliThimmaiah** [trupti-dhall/Harman#2]
Please create Template for News Section. It should have the following Fields

Title
Body
Language(Default language Selector)
Tags(Term Reference)

and Name this Template as News Carousel

**Comment by ank1330** [comment]
@MuruliThimmaiah 
Created News Content type for news carousel.
Added following fields:
Title
Body
Language(Default language Selector)
There is no need of "tags field" for categorization based on language, if you have language field.
The language which you will select at the time of creating news, like if you have selected china as language  will show only on china page unless and until you don't drag and drop the block to respective pages using awe content.
