### ISSUE TITLE
No text limitation

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#20]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
step 3 :: Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/solutions
Step 4 : In device , Iphone
Step 5 : Click edit icon .
Step 6 : On edit page added huge description to Description field.
Step 7 : Observed that there is no restriction on description text.
Step 8 : Images are overlapped with each other.
Step 9 : Attached screenshot
![image](https://cloud.githubusercontent.com/assets/23308564/20090296/603da5fe-a5b2-11e6-8679-53259f337838.png)

**Comment by trupti-dhall** [comment]
Added text limitation.

**Comment by debasis123nandi** [comment]
Its working fine now .
