### ISSUE TITLE
Text content is overlapping the images

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#22]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/solutions
Step 4 : In device , Iphone
step 5 : It is observed that images are getting overlapped 
step 6 :  screenshots

![image](https://cloud.githubusercontent.com/assets/23308564/20337745/03df40d6-abf9-11e6-8714-02654b5b10d0.png)

**Comment by arpita123das** [comment]
Issue is not replicating from my end,hence closing this issue
