### ISSUE TITLE
Content text slideshowing is different 

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#23]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/solutions
Step 4 : In device , Iphone
step 5 : It is observed that style of showing the content in device Iphone is different from PC as compared.
step 6 ; screenshots

![image](https://cloud.githubusercontent.com/assets/23308564/20341585/d136e922-ac0c-11e6-9dc7-b8326841762f.png)

![image](https://cloud.githubusercontent.com/assets/23308564/20341605/e47d3d7e-ac0c-11e6-8b56-41e6a46b16b8.png)

**Comment by arpita123das** [comment]
Issue resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/solutions
![solutions](https://cloud.githubusercontent.com/assets/23329067/20137132/c77b896a-a69e-11e6-93b6-a15adf3ce8ff.PNG)
