### ISSUE TITLE
Text is overlapping the image

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#24]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/lifestyle-audio
Step 4 : In device , Iphone
Step 5 : It is observed that text is overlapping the banner image as compared with PC
Step 6 :; screenshots
![image](https://cloud.githubusercontent.com/assets/23308564/20341747/8686e386-ac0d-11e6-9b43-af1e2b8c9a3c.png)

Step 7 : As shown in device, PC
![image](https://cloud.githubusercontent.com/assets/23308564/20341760/8e105baa-ac0d-11e6-903a-a723ed99846d.png)

**Comment by arpita123das** [comment]
Issue is resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/lifestyle-audio
![life-style](https://cloud.githubusercontent.com/assets/23329067/20133840/17c8b0ec-a68f-11e6-827d-3ad8d438d898.PNG)
