### ISSUE TITLE
Images are getting stretched out

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#25]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: 
Step 4 : In device ,PC
Step 5 : Open in browser, Google Chrome
Step 6 : It is observed that the image highlighted is overstretched.
Step 7 :; screenshots
![image](https://cloud.githubusercontent.com/assets/23308564/20342221/974a288e-ac0f-11e6-8bf4-89027afa43ac.png)
Step 8 : Naviagte to url : 
Step 9 : In device , Iphone
Step 10 : It is observed that image is over compressed .
Step 11 : Screenshot
![image](https://cloud.githubusercontent.com/assets/23308564/20342282/d650ab5c-ac0f-11e6-856d-fa0c0708a1a1.png)

**Comment by arpita123das** [comment]
When image will  be provided by client,then this issue will be resolved.
