### ISSUE TITLE
No proper directed link attached

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#26]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123 
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/lifestyle-audio
Step 4 : In device , PC
Step 5 : Open in browser, google chrome
Step 6 : On comparing with harman.com , it is observed that on the above mention page the options on the images are different and navigating to anonymous websites and the "all news" icon is  navigating to the above url (given) . 
Step 7 : Screenshot attached
![image](https://cloud.githubusercontent.com/assets/23308564/20259685/2ec55624-aa7c-11e6-92cb-326d980de3a8.png)
![image](https://cloud.githubusercontent.com/assets/23308564/20259691/4123178e-aa7c-11e6-9e8e-c979d714cae1.png)

**Comment by trupti-dhall** [comment]
Provided proper link

**Comment by debasis123nandi** [comment]
Its working fine
