### ISSUE TITLE
No restriction in addition of texts

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#28]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
step 3 :: Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/solutions
Step 4 : In device , PC
Step 5: Open in Browser,Google Chrome
Step 6 : Click edit icon .
Step 7 : On edit page added huge description to Description field.
Step 8 : Observed that there is no restriction on description text.
Step 9 : Attached screenshot
![image](https://cloud.githubusercontent.com/assets/23308564/20095415/6acf21d2-a5cb-11e6-8473-2e09f9f2243f.png)

![image](https://cloud.githubusercontent.com/assets/23308564/20095533/dd157f48-a5cb-11e6-9af5-ec2c97dcbc38.png)
Step 10: While checking in device ,Iphone 
Step 11 : Observed that there is no restriction on description text.
Step 12: Screenshot attached
![image](https://cloud.githubusercontent.com/assets/23308564/20095600/1faea000-a5cc-11e6-917c-76497152f70c.png)

**Comment by debasis123nandi** [comment]
In Addition ::
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
step 3 :: Navigate to the url: https://wipro48ocphrfau.devcloud.acquia-sites.com/luxury-audio
Step 4 : In device , PC
Step 5: Open in Browser,Google Chrome
Step 6 : Click edit icon .
Step 7 : On edit page added huge description to Description field.
Step 8 : Observed that there is no restriction on description text.
Step 9 : Attached screenshot
![image](https://cloud.githubusercontent.com/assets/23308564/20170783/ad5b2fda-a753-11e6-8471-efbc0874fb66.png)

https://wipro48ocphrfau.devcloud.acquia-sites.com/lifestyle-audio
![image](https://cloud.githubusercontent.com/assets/23308564/20170801/c392585a-a753-11e6-9218-9caa97cb3736.png)

**Comment by trupti-dhall** [comment]
Applied 300 text restriction.

**Comment by debasis123nandi** [comment]
Its working fine.
