### ISSUE TITLE
Logos in partner section is crossing the margin 

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#30]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/inspired
Step 4 : In device , Iphone
Step 6 : On scrolling down to partners section in the given page , it is observed that logos in partner section is crossing the margin 
Step 7 : screenshots
![image](https://cloud.githubusercontent.com/assets/23308564/20342668/60752050-ac11-11e6-8808-76c317e91c08.png)

**Comment by arpita123das** [comment]
Issue is resolved:
url:http://wipro48ocphrfau.devcloud.acquia-sites.com/inspired

![logo1](https://cloud.githubusercontent.com/assets/23329067/20130881/d3c81c0c-a67f-11e6-8430-ddfa1f4189cf.PNG)

**Comment by debasis123nandi** [comment]
Its working fine
