### ISSUE TITLE
Issues with logos in partner section

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#31]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/inspired
Step 4 : In device , PC
Step 5: Open in browser,Google Chrome
Step 6  : It is observed that logos in partner section , some are directed to there respective  links and some are not .
Step 7: Screenshot attached
![image](https://cloud.githubusercontent.com/assets/23308564/20260230/b5694bc0-aa7e-11e6-8578-b358a4ac710c.png)

**Comment by debasis123nandi** [comment]
In Addition ,
Navigate to : https://wipro48ocphrfau.devcloud.acquia-sites.com/lifestyle-audio
Scroll down to Automotive brands , and lifestyle audio brands,

Browser : IE
It is observed that Logos are not allign.

![image](https://cloud.githubusercontent.com/assets/23308564/20698160/101c2b30-b625-11e6-8248-c7d2dd13c708.png)

![image](https://cloud.githubusercontent.com/assets/23308564/20698175/286b62d2-b625-11e6-8ad7-c819aaf3d327.png)

**Comment by sahu-sneha** [comment]
On live site also these logos are not redirected to an external link

**Comment by debasis123nandi** [comment]
In addition ,
URL :  http://wipro48ocphrfau.devcloud.acquia-sites.com/china/inspired
Highlighted logos donot have link
![image](https://cloud.githubusercontent.com/assets/23308564/20743478/a0367284-b6fc-11e6-923e-023534bdad5a.png)


And previous issue exist in lifestyle audio , china and english 


Below shown image icons are not allign
![image](https://cloud.githubusercontent.com/assets/23308564/20743573/2d24ce34-b6fd-11e6-891b-567ab2251a6b.png)

**Comment by trupti-dhall** [comment]
Duplicate of issue -68

**Comment by debasis123nandi** [comment]
copied from 68 , refer 68 for clear images

Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/inspired
Step 4 : In device PC
Step 5 : Open in browser, Mozilla firefox
Step 6 : Scroll down to the PARTNER Section
Step 7 : It is observed that logos are not capturing the whole region
**Please check in china site also

Step 8 :
Screenshot attached

image

@trupti-dhall ,Issue still exist in : http://wipro48ocphrfau.devcloud.acquia-sites.com/china/inspired
image

**Comment by debasis123nandi** [comment]
Its fine , as discussed with @sahu-sneha and @trupti-dhall
