### ISSUE TITLE
Menu and arrows are no align 

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#33]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/supply-chain
Step 4 : In device , PC
Step 5 : Open in browser Google Chrome
Step 6 : Scroll down to the block section, it is observed that the text links and there respective arrows are not alligned.
Step 7 :  Screenshots attached
![image](https://cloud.githubusercontent.com/assets/23308564/20342858/1ea232ac-ac12-11e6-9dc5-b5d622b2ea3c.png)

Step 8 : On comparing the same in harman.com, Screenshot attached ,
![image](https://cloud.githubusercontent.com/assets/23308564/20342888/4422ac32-ac12-11e6-92e5-40c1594d24de.png)

**Comment by debasis123nandi** [comment]
In addition to the same , 
Link text starting font should be capital or same , and theer should be proper spacinf between 2 links .

**Comment by arpita123das** [comment]
Issue is resolved
URL: http://wipro48ocphrfau.devcloud.acquia-sites.com/supply-chain.
![chain](https://cloud.githubusercontent.com/assets/23329067/20133335/2cb42a1a-a68d-11e6-949b-2c8be47a2b9e.PNG)

**Comment by debasis123nandi** [comment]
Its working fine

**Comment by debasis123nandi** [comment]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user

Step 2 : Login as editor. editor/wipro@123

Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/connected-car
             and , http://wipro48ocphrfau.devcloud.acquia-sites.com/china/connected-car

Step 4 : In device , Ipad

step 5 : It is observed that inside Partner's tab , the arrows are not align with the links

Step 6 : Screenshot attached
![image](https://cloud.githubusercontent.com/assets/23308564/20471375/fecf3eca-afd6-11e6-8e4f-01bcbb5d1f30.png)

**Comment by arpita123das** [comment]
its look like same as harman livesite.
close this issue

**Comment by debasis123nandi** [comment]
As discussed with @arpita123das , "its look like same as harman livesite."
