### ISSUE TITLE
 links should directed to there appropriate pdf s or URLs.

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#34]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url:  http://wipro48ocphrfau.devcloud.acquia-sites.com/supply-chain
Step 4 : In device , PC
Step 5 : Open in browser,Google Chrome
Step 6: It is observed that all below highlighted links are not directed to there appropriate pdfs or URLs.
Step 7 : 
![image](https://cloud.githubusercontent.com/assets/23308564/20260819/522a0eac-aa81-11e6-8b8d-0e26d9e839b8.png)

Step 8: Navigate to Url : http://wipro48ocphrfau.devcloud.acquia-sites.com/career

![image](https://cloud.githubusercontent.com/assets/23308564/20260800/3e700f9c-aa81-11e6-8019-b0e9674e2a8c.png)

**Comment by debasis123nandi** [comment]
In Addition ,

url :: http://wipro48ocphrfau.devcloud.acquia-sites.com/career
login as :: editor/user
browser :: chrome
All the highlighted items , in the below shown screenshot should be directed to there specific url's.
![image](https://cloud.githubusercontent.com/assets/23308564/20137093/8f2706d4-a69e-11e6-96ad-543ccb311b1d.png)

**Comment by trupti-dhall** [comment]
Provided all valid links

**Comment by debasis123nandi** [comment]
It is fine with : url: http://wipro48ocphrfau.devcloud.acquia-sites.com/supply-chain

But Career page is not opening

**Comment by trupti-dhall** [comment]
New url:http://wipro48ocphrfau.devcloud.acquia-sites.com/careers

**Comment by debasis123nandi** [comment]
Its fine with careers site 
BUT,

@arpita123das @trupti-dhall ,
url : http://wipro48ocphrfau.devcloud.acquia-sites.com/supply-chain
browser : IE
blocks ar not allign and arrows are not allign with the texts link
![image](https://cloud.githubusercontent.com/assets/23308564/20743295/9647e2fe-b6fb-11e6-8e34-37ddc3031b3d.png)

**Please check with China site also

**Comment by trupti-dhall** [comment]
Expected behavior of link text.Height is aligned properly.

**Comment by trupti-dhall** [comment]
![image](https://cloud.githubusercontent.com/assets/22929369/20754771/7ee6713e-b732-11e6-9cac-519d71cfda8c.png)

**Comment by debasis123nandi** [comment]
Its fine now
