### ISSUE TITLE
Name and Email fields has no validation

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#35]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/contact-us
Step 4 : In device , PC
Step 5 : Open in browser,Google Chrome
Step 6: On filling the form with name field containing any value and email field as containing any value is showing successful message.
Step 7: Its observed that there is no validation in this 2 fields .

Step 8 : Screenshot attached

![image](https://cloud.githubusercontent.com/assets/23308564/20261062/3c23ac84-aa82-11e6-8a82-2c1b95a4e6c0.png)

**Comment by ank1330** [comment]
@debasis123nandi  I have added validation on name and email field both on China and main website.
http://wipro48ocphrfau.devcloud.acquia-sites.com/contact-us
http://wipro48ocphrfau.devcloud.acquia-sites.com/china/contact-us

**Comment by debasis123nandi** [comment]
Validations are fine now , but the mail that is been entered is not sending any acknowledgement mail to the given emailid.

**Comment by trupti-dhall** [comment]
@debasis.Close this issue.As  mail cannot be sent through free acquia account.

**Comment by debasis123nandi** [comment]
As discussed with @trupti-dhall , As mail cannot be sent through free acquia account.
