### ISSUE TITLE
Part of text is getting overridden  

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#36]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/career
Step 4 : In device , Iphone
Step 6 : On scrolling down to block section, it is observed that  few text as shown highlighted below are getting overlapped.
Step 7 ; screenshots
![image](https://cloud.githubusercontent.com/assets/23308564/20343109/217eefbe-ac13-11e6-8997-f3250674c035.png)

Step 8 : Naviagate to same url : http://wipro48ocphrfau.devcloud.acquia-sites.com/career
Step 9 : In device ,Pc
Step 10 : Open in browser, Google Chrome
Step 11 : Screenshot attached
![image](https://cloud.githubusercontent.com/assets/23308564/20343165/55f38b38-ac13-11e6-93c3-01fc3c2615e9.png)

**Comment by arpita123das** [comment]
Issue resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/career
![career](https://cloud.githubusercontent.com/assets/23329067/20165462/736afbfe-a733-11e6-8e5a-581b6d17c039.PNG)

**Comment by debasis123nandi** [comment]
Its working fine now
