### ISSUE TITLE
Edit sign should be highlighted 

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#38]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: https://wipro48ocphrfau.devcloud.acquia-sites.com/home
Step 4 : In device , PC
Step 5 : Open in browser,GoogleChrome
Step 6 : Scroll down to the about section 
Step 7: Click the edit option in sustainability
Step 8 : Its observed that edit page is opened, but edit option is not visible on the sustainable image.
Step 9 : 
![image](https://cloud.githubusercontent.com/assets/23308564/20261490/0901067e-aa84-11e6-9b96-d30d2c37a1b3.png)

**Comment by arpita123das** [comment]
Issue resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com
![home](https://cloud.githubusercontent.com/assets/23329067/20591655/ccdf31c4-b24f-11e6-95ee-62e61d5c892c.PNG)

**Comment by debasis123nandi** [comment]
Its working fine and edit symbol is been highlighted
