### ISSUE TITLE
Images and links in thumbnails is not similar

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#43]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/china
Step 4 : In device , PC
Step 5 : Open in browser, Google Chrome
step 6 : It is observed that on clicking the thumbnail icon the images and links highlighted below is not similar as in harman.com
step 7 :: screenshot
![image](https://cloud.githubusercontent.com/assets/23308564/20293327/6125ccbc-ab1b-11e6-9446-c57c37dbf1f9.png)
Step 8 : On comparing with Harman.com ,
![image](https://cloud.githubusercontent.com/assets/23308564/20205602/53798f36-a800-11e6-89fb-921d30f26ee0.png)

**Comment by trupti-dhall** [comment]
Expected behavior

**Comment by debasis123nandi** [comment]
As discussed with @trupti-dhall  , its an expected behaviour
