### ISSUE TITLE
Heading of the sub menus is in english

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#47]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/china/lifestyle-audio
Step 4 : In device , PC
Step 5 : Open in browser, Google Chrome
step 6 : Navigate to the url ::http://wipro48ocphrfau.devcloud.acquia-sites.com/china/lifestyle-audio
step 7 : On scrolling down to the web page its observed that heading of the sub menus is in english, which should be in chinese(as compared with harman.com)
step 8 :; screenshots 
![image](https://cloud.githubusercontent.com/assets/23308564/20264092/ce97ec30-aa8f-11e6-9213-a10c6496f57c.png)

**Comment by debasis123nandi** [comment]
Still the issue is there 

![image](https://cloud.githubusercontent.com/assets/23308564/20669632/426b9498-b59b-11e6-8205-b3b76e94333c.png)

**Comment by trupti-dhall** [comment]
expected behavior.As av is not a word ,its just a abbreviation so it cannot be translate  to chineses.

**Comment by debasis123nandi** [comment]
As discussed with @trupti-dhall  , its an expected behaviour
