### ISSUE TITLE
Should map to proper link

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#50]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/china/lifestyle-audio
Step 4 : In device , PC
Step 5 : Open in browser Google Chrome
step 6 : It is observed that on clicking the tooltip images , its not navigating to respective webpages.
step 7 :; screenshots  
![image](https://cloud.githubusercontent.com/assets/23308564/20261934/05ccf966-aa86-11e6-8c53-2f030f1471f7.png)

**Comment by trupti-dhall** [comment]
Review it  and close if working well

**Comment by debasis123nandi** [comment]
as discussed with @trupti-dhall ,  @sahu-sneha  , its working well
