### ISSUE TITLE
No navigating sticky menu .

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#51]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/china/sustainability
Step 4 : In device , PC
Step 5 : Open in browser Google Chrome
Step 6 : Scroll up and down the whole web page
Step 7 : It is observed that there is no navigating sticky menu .
Step8 ; screenshots
![image](https://cloud.githubusercontent.com/assets/23308564/20337861/a239fb40-abf9-11e6-84e1-0868b4f145e5.png)

**Comment by arpita123das** [comment]
Issue Resolved.
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/china/sustainability
![china](https://cloud.githubusercontent.com/assets/23329067/20591573/296c14da-b24f-11e6-9a15-eb01fbd480f6.PNG)

**Comment by debasis123nandi** [comment]
Its working fine now
