### ISSUE TITLE
Overview option should not be present in Create solution page

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#53]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/node/add/solution
Step 4 : In device , PC
Step 5 : Open in browser Google Chrome
Step 6 : Navigate to CONTENT --> ADD CONTENT --> SOLUTION
Step 7: It is observed that create solution page opens
Step 8 : Select the language (english)
Step 9 : Select page category (Solution)
Step 10 : Select Solution Category
Step 11 : A dropdown appears
Step 12 : It is observed that overview option is present , in which adding of items/blocks are restricted .
step 13; Screenshots

![image](https://cloud.githubusercontent.com/assets/23308564/20338268/0cfe9db2-abfc-11e6-833c-3da9cd73cae9.png)

**Comment by trupti-dhall** [comment]
Duplicate of issue 56

**Comment by ank1330** [comment]
@debasis123nandi  Issue has been resolved

**Comment by debasis123nandi** [comment]
Its working fine ..
