### ISSUE TITLE
Description is crossing the margin and hence have no limitations.

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#54]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/node/add/solution
Step 4 : In device , PC
Step 5 : Open in browser Google Chrome
Step 6 : Navigate to CONTENT --> ADD CONTENT --> SOLUTION
Step 7: It is observed that create solution page opens
Step 8 : Select the language (english)
Step 9 : Select page category (Solution)
Step 10 : Select Solution Category (CONNECTED CARS)
Step 11 : Enter a title name 
Step 12 : Upload a image
Step 13 : Enter huge text in description.
Step 14 : Save  the changes
Step 15 : Navigate to url : http://wipro48ocphrfau.devcloud.acquia-sites.com/connected-car
Step 16 : Scroll down to the new content that is been recently added
Step 17 : It is observed that new solution content is added with title , image , but the description is crossing the margin and hence have no limitations.
Step 18 :  Screenshots
![image](https://cloud.githubusercontent.com/assets/23308564/20338484/6830e70c-abfd-11e6-8292-8ec6ccd8c247.png)

**Comment by arpita123das** [comment]
Issue Resolved.
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/connected-car
![pclass](https://cloud.githubusercontent.com/assets/23329067/20562928/379f2afe-b1ac-11e6-928f-40adc82041ae.PNG)
