### ISSUE TITLE
Issue with Lifestyle audio page, when new content is added

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#55]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/node/add/solution
Step 4 : In device , PC
Step 5 : Open in browser Google Chrome
Step 6 : Navigate to CONTENT --> ADD CONTENT --> SOLUTION
Step 7: It is observed that create solution page opens
Step 8 : Select the language (english)
Step 9 : Select page category (Solution)
Step 10 : Select Solution Category (LIFESTYLE-AUDIO)
Step 11 : Enter a title name
Step 12 : Upload a image
Step 13 : Enter huge text in description.
Step 14 : Save the changes
Step 15 : Navigate to url : http://wipro48ocphrfau.devcloud.acquia-sites.com/lifestyle-audio
Step 16 : Scroll down to the new content that is been recently added
Step 17 : It is observed that new solution content is added with title , image , but the description is crossing the margin and hence have no limitations.
Step 18 : Screenshots
![image](https://cloud.githubusercontent.com/assets/23308564/20376972/8463a70c-acb1-11e6-9660-07805d26d19f.png)
Step 19 : Edit the new added content
Step 20 : It is observed that the Edit option is being overlapped by the next content as  shown.
Step 21: Screenshot
![image](https://cloud.githubusercontent.com/assets/23308564/20377046/079721b2-acb2-11e6-90bf-82d51d30abf1.png)

**Comment by arpita123das** [comment]
Issue resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/lifestyle-audio
![lifestyle](https://cloud.githubusercontent.com/assets/23329067/20377360/c0255ad0-acb4-11e6-96bc-5a625264fef8.PNG)

**Comment by arpita123das** [comment]
After code commit it will reflect.

**Comment by debasis123nandi** [comment]
Text when added , they are getting inside the region and are limited , but the edit sign is not opening the edit page and its been overlapped .
Issue 1 with text inside region is solved , but issue 2 with the edit sign is still exist

**Comment by arpita123das** [comment]
Issue resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/lifestyle-audio
![audio](https://cloud.githubusercontent.com/assets/23329067/20593259/b3d905a8-b257-11e6-9f96-18ff5e2b97f5.PNG)

**Comment by debasis123nandi** [comment]
Its working fine
