### ISSUE TITLE
Overview option in Solution Category should not be present

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#56]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: https://wipro48ocphrfau.devcloud.acquia-sites.com/node/add/news
Step 4 : In device , PC
Step 5 : Open in browser Google Chrome
Step 6 : Navigate to CONTENT --> ADD CONTENT -->NEWS AND VIEWS
Step 7: It is observed that create news and views page opens
Step 8 : Select the language (english)
Step 9 : Select page 
Step 10 : Select Ranking
Step 11 : Enter a title name
Step 12 : Upload a image
Step 13 : Select solution category
Step 14 : It is observed that a drop down appears with 5 option , which should be 4.
Step 15 : Screenshots

![image](https://cloud.githubusercontent.com/assets/23308564/20378592/181c4c78-acbd-11e6-90b4-24e4a7008cfc.png)

**Comment by ank1330** [comment]
@debasis123nandi  Issue has been resolved.

**Comment by debasis123nandi** [comment]
Its working fine ..
