### ISSUE TITLE
URL is not the same as the title (INNOVATION)

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#57]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/china/node/78
Step 4 : In device , PC
Step 5 : Open in browser, Google Chrome
step 6 : It is observed that site URL is not the same as the title (INNOVATION)

![image](https://cloud.githubusercontent.com/assets/23308564/20379917/be6d73fc-acc4-11e6-9964-a0712adc650d.png)

**Comment by sahu-sneha** [comment]
Visit the url using the alias : http://wipro48ocphrfau.devcloud.acquia-sites.com/china/innovation

**Comment by debasis123nandi** [comment]
Its  fine now
