### ISSUE TITLE
Milestone title overlapping with year

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#58]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/milestones
Step 4 : In device , Ipad
step 5 : It is observed that Milestone title is within a blue colour bar and the year is getting overlapped with the blue bar.
Step 6 : Screenshots attached
![image](https://cloud.githubusercontent.com/assets/23308564/20470566/bbf7f8a0-afcf-11e6-9aeb-366d3a1d95b7.png)

**Comment by arpita123das** [comment]
Issue Resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/milestones
![milestone](https://cloud.githubusercontent.com/assets/23329067/20587419/8394303a-b233-11e6-8807-3d2aba6c7cbe.PNG)

**Comment by debasis123nandi** [comment]
Its fine now
