### ISSUE TITLE
Image slider is overlapped with the texts 

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#60]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/career
Step 4 : In device , PC ,
Step 5 : Open in browser Google Chrome
Step 6 : Scroll down to CAREER NEWS section,
STEP 7 :  it is observed that the image slider is overlapped with the texts 
Step 8 : Screenshots attached

![image](https://cloud.githubusercontent.com/assets/23308564/20551153/ce9972ba-b162-11e6-961f-ddf52cac6f43.png)

Step 9 : Issue also exist in Ipad

**Comment by arpita123das** [comment]
Issue Resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/career
![slider](https://cloud.githubusercontent.com/assets/23329067/20562788/80e3e61a-b1ab-11e6-8d8a-95daf53ba0d2.PNG)

**Comment by debasis123nandi** [comment]
Its working fine now

**Comment by trupti-dhall** [comment]
Height is not matching with live harman

**Comment by debasis123nandi** [comment]
Its fine now
