### ISSUE TITLE
Video is not running 

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#61]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: https://wipro48ocphrfau.devcloud.acquia-sites.com/china/connected-car
Step 4 : In device , Iphone and Ipad
Step 5 : Its observed that the video is not running in both the devices as its happening in PC
Step 6 :Screenshot attached

![image](https://cloud.githubusercontent.com/assets/23308564/20595381/b6f6a44a-b25f-11e6-9fce-0d0c1f92e5e7.png)

**Comment by trupti-dhall** [comment]
Net work related issue close it.

**Comment by debasis123nandi** [comment]
Its working fine ..
