### ISSUE TITLE
China page having english title heading

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#62]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: https://wipro48ocphrfau.devcloud.acquia-sites.com/china/connected-car
Step 4 : In device , PC
Step 5 : Open in browser,GoogleChrome
Step 6 : Scroll down to the TELEMATICS
Step 7 : Its observed that China page having english title heading
Step 8 :
Screenshot attached 
![image](https://cloud.githubusercontent.com/assets/23308564/20595549/569add04-b260-11e6-9758-02cde9c4a81b.png)

Step 9 : It is observed that edit is not assign with its respective arrow
Step 10 : Screenshot attached
![image](https://cloud.githubusercontent.com/assets/23308564/20595826/8d289b30-b261-11e6-8c4b-32807dc66f62.png)

**Comment by debasis123nandi** [comment]
url : https://wipro48ocphrfau.devcloud.acquia-sites.com/china/connected-car
URL issue , the links are navigating to improper url (example : ......#345)
![image](https://cloud.githubusercontent.com/assets/23308564/20742996/bf1b5bae-b6f9-11e6-8a08-183a8f6f4025.png)

**Comment by trupti-dhall** [comment]
Not required you can close it.

**Comment by debasis123nandi** [comment]
as discussed with @trupti-dhall  , its not required
therefore, closing the issue
