### ISSUE TITLE
No map found

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#63]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/china/contact-us
Step 4 : In Ipad and in Iphone
Step 5 : Scroll down to the MAP section
Step 6 : Its observed that no map is found
Step 7 :
Screenshot attached

![image](https://cloud.githubusercontent.com/assets/23308564/20616342/8971d38e-b307-11e6-8ef7-c602bd6c0fa9.png)

**Please look into the normal site also

**Comment by trupti-dhall** [comment]
Newtwork related issue.close it

**Comment by debasis123nandi** [comment]
@trupti-dhall , as discussed , its an network issue and working fine .
