### ISSUE TITLE
Images are not of equal size

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#64]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/china/careers
Step 4 : In device PC
Step 5 : Open in browser, Google Chrome
Step 6 : Scroll down to the last secton
Step 7 : Its observed that two highlighted images are not of equal size
Step 8 :
Screenshot attached

![image](https://cloud.githubusercontent.com/assets/23308564/20616424/4b2819de-b308-11e6-84e8-a68a16506df1.png)

**Comment by arpita123das** [comment]
Issue resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/china/careers
![career](https://cloud.githubusercontent.com/assets/23329067/20699299/96e4ceb8-b62c-11e6-8cc1-b5af8be22b74.PNG)

**Comment by debasis123nandi** [comment]
Its fine now
