### ISSUE TITLE
Image icons (highlighted) are not allign on the image 

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#65]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/china/lifestyle-audio
Step 4 : In device PC
Step 5 : Open in browser, Google Chrome
Step 6 : Scroll down to the 汽車BRANDED AUDIO section
Step 7 : Its observed that image icons (highlighted) are not allign on the image 
Step 8 :
Screenshot attached

![image](https://cloud.githubusercontent.com/assets/23308564/20616499/b3f00666-b308-11e6-8138-42f6013fb70e.png)

**Please look into the normal site as well as in other images.

Step 9 : As shown in harman.com
Step 10 :  screenshot attached
![image](https://cloud.githubusercontent.com/assets/23308564/20616535/ed4b97a4-b308-11e6-9884-ec56acd895f7.png)

**Comment by arpita123das** [comment]
Issue Resolved:
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/china/lifestyle-audio
![china1](https://cloud.githubusercontent.com/assets/23329067/20699264/6bfd92e8-b62c-11e6-81ab-c4091e071acf.PNG)

**Comment by debasis123nandi** [comment]
url : 
http://wipro48ocphrfau.devcloud.acquia-sites.com/china/lifestyle-audio
Still not allign
![image](https://cloud.githubusercontent.com/assets/23308564/20741070/e10c5170-b6ed-11e6-9a6d-caf7197d6d92.png)

url https://wipro48ocphrfau.devcloud.acquia-sites.com/lifestyle-audio

![image](https://cloud.githubusercontent.com/assets/23308564/20741107/18dd88f8-b6ee-11e6-93f6-f8efb7f60d66.png)

**Comment by trupti-dhall** [comment]
As spoke to designer @arpita123das , suggested this as expected behavior.

**Comment by debasis123nandi** [comment]
@trupti-dhall ,But in Harman .com , its like ::

![image](https://cloud.githubusercontent.com/assets/23308564/20749477/842ce534-b718-11e6-921d-3ebc60f30a10.png)

**Comment by trupti-dhall** [comment]
Yes. i know  that is not the right way.

**Comment by debasis123nandi** [comment]
as discussed with @trupti-dhall , "it is not the right way."
Hence closing it
