### ISSUE TITLE
Logos are not capturing the whole region

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#68]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/inspired
Step 4 : In device PC
Step 5 : Open in browser, Mozilla firefox
Step 6 : Scroll down to the PARTNER Section
Step 7 : It is observed that logos are not capturing the whole region
**Please check in china site also

Step 8 :
Screenshot attached

![image](https://cloud.githubusercontent.com/assets/23308564/20620681/e4b759bc-b320-11e6-92a0-692aa2b77180.png)

**Comment by arpita123das** [comment]
Issue Resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/inspired
![logo](https://cloud.githubusercontent.com/assets/23329067/20705660/cd9898dc-b649-11e6-88a6-4a73368843ea.PNG)

**Comment by debasis123nandi** [comment]
@trupti-dhall ,Issue still exist in : http://wipro48ocphrfau.devcloud.acquia-sites.com/china/inspired
![image](https://cloud.githubusercontent.com/assets/23308564/20741164/72800502-b6ee-11e6-906e-2ace72b950c4.png)

**Comment by debasis123nandi** [comment]
closing it , as a duplicate issue 31 is active
