### ISSUE TITLE
Banner caption on the banner image is getting overlapped

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#69]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: https://wipro48ocphrfau.devcloud.acquia-sites.com/
Step 4 : In device Ipad. Iphone
Step 5 : It is observed that the tooltip text on the banner image is getting overlapped with the margin
**Please check in china site also

Step 6 :
Screenshot attached

![image](https://cloud.githubusercontent.com/assets/23308564/20622536/603b192c-b329-11e6-875a-7c239d04e02c.png)

**Comment by arpita123das** [comment]
Issue resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com

**Comment by debasis123nandi** [comment]
@arpita123das 

**Issue still exist** : https://wipro48ocphrfau.devcloud.acquia-sites.com/
![image](https://cloud.githubusercontent.com/assets/23308564/20707887/64330206-b653-11e6-921a-a6e580f9667b.png)

**Comment by debasis123nandi** [comment]
Its fine now
