### ISSUE TITLE
News & Views block dynamic tagging

### ISSUE THREAD

**Issue by trupti-dhall** [trupti-dhall/Harman#71]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: https://wipro48ocphrfau.devcloud.acquia-sites.com
Step 4 : In device , PC
Step 5 : Open in browser,GoogleChrome
Step 6 : Scroll down to the News & Views block
Step 7 : Its observed that tagging of block is not proper..(corporate is not available)
Step 8 : In harman live site  it is observed that block has been tagged dynamically irrespective of category.
![news views](https://cloud.githubusercontent.com/assets/22929369/20668487/1ffc19d8-b595-11e6-91f7-a06f2d7ac1a6.png)

**Comment by ank1330** [comment]
@debasis123nandi 
I have added one field (news views tags) while adding or editing content of news and views.
You can add  required tag in that field and then you will be able to see proper tag as same as live site(harman.com)

Qc'ed on http://wipro48ocphrfau.devcloud.acquia-sites.com/

**Comment by debasis123nandi** [comment]
Its fine now
