### ISSUE TITLE
Logo link is not navigating to respective site

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#72]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: https://wipro48ocphrfau.devcloud.acquia-sites.com/home
Step 4 : In device PC
Step 5 : Open in IE
Step 6 : Scroll down to ECOSYSTEM --> PARTNER section
Step 7 : Navigate to volwagen logo
Step 8 : It is observed that the logo link is not navigating to volswagen site as compared with other logos , rather its directing to : http://www.bmw.com/com/en/newvehicles/7series/sedan/2015/showroom/innovative_functionality.html
**Please check in china site also

Step 9 :
Screenshot attached

![image](https://cloud.githubusercontent.com/assets/23308564/20695875/48bf00da-b615-11e6-8b08-002f2753af3c.png)

**Comment by trupti-dhall** [comment]
Provided valid link.Please check it.

**Comment by debasis123nandi** [comment]
Its fine now
