### ISSUE TITLE
Text area height is variable 

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#77]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: https://wipro48ocphrfau.devcloud.acquia-sites.com/solutions
Step 4 : In device PC
Step 5 : Open in IE
Step 6 : It is observed that text area height is variable 

Step 7 :
Screenshot attached

![image](https://cloud.githubusercontent.com/assets/23308564/20697541/003f4558-b620-11e6-9f6b-20e152aa1926.png)

**Comment by arpita123das** [comment]
Issue Resolved
URL:https://wipro48ocphrfau.devcloud.acquia-sites.com/solutions

**Comment by debasis123nandi** [comment]
Its fine now
