### ISSUE TITLE
No china news link

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#79]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: https://wipro48ocphrfau.devcloud.acquia-sites.com/china
Step 4 : In device , PC
Step 5: Open in browser,Google Chrome/IE/Mozilla
Step 6 : It is observed that there is no china news link in menu bar , as present in english site
Step 7: Screenshot attached
![image](https://cloud.githubusercontent.com/assets/23308564/20705594/89b89a40-b649-11e6-82ec-81bc8a67779d.png)

Step 8 : 
![image](https://cloud.githubusercontent.com/assets/23308564/20705620/a357d0b0-b649-11e6-9273-93219bd0c863.png)

**Comment by trupti-dhall** [comment]
Expected behaviour.Not present in harman live also

**Comment by debasis123nandi** [comment]
as discussed with @trupti-dhall  , its an expected behaviour
