### ISSUE TITLE
Arrows are not behaving as links

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#81]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: https://wipro48ocphrfau.devcloud.acquia-sites.com/news
Step 4 : In device , PC
Step 5: Open in browser,Google Chrome/IE/Mozilla
Step 6 : It is observed that arrows are not behaving as links and not navigating to any URLs and there are no edit icons to edit the news 
Step 7: Screenshot attached
![image](https://cloud.githubusercontent.com/assets/23308564/20739810/17edd1a0-b6e4-11e6-8c4b-a1c02433fb69.png)

**Please check china site

**Comment by debasis123nandi** [comment]
Link highlighted should navigate to proper url
![image](https://cloud.githubusercontent.com/assets/23308564/20752329/d23dd306-b726-11e6-8d55-f9a11b05522d.png)

**Comment by trupti-dhall** [comment]
please check this.done

**Comment by debasis123nandi** [comment]
url : https://wipro48ocphrfau.devcloud.acquia-sites.com/china/news
Highlighted text should not be bold
![image](https://cloud.githubusercontent.com/assets/23308564/20753024/524f2b64-b72a-11e6-9cca-7035b6759e16.png)

**Comment by debasis123nandi** [comment]
Its still as earlier 

![image](https://cloud.githubusercontent.com/assets/23308564/20830183/5bc3108a-b8a5-11e6-8415-ee3564ae874a.png)

**Comment by debasis123nandi** [comment]
As earlier mentioned by @trupti-dhall , this issue is duplicate of #82 ,
Hence closing the issue
