### ISSUE TITLE
Chinese news page is not showing proper

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#82]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/china/news
Step 4 : In device , PC
Step 5: Open in browser,Google Chrome/IE/Mozilla
Step 6 : It is observed that chinese news page is not showing proper and the footer links are containing nodes
Step 7: Screenshot attached
![image](https://cloud.githubusercontent.com/assets/23308564/20740554/faaabf58-b6e9-11e6-9bca-436b61b466f9.png)

![image](https://cloud.githubusercontent.com/assets/23308564/20740605/66dd5384-b6ea-11e6-9bff-a389c15243d3.png)

**Comment by arpita123das** [comment]
Issue resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/china/news
![media](https://cloud.githubusercontent.com/assets/23329067/20826055/5e0a3826-b88e-11e6-8180-7b4dba506daf.PNG)

**Comment by debasis123nandi** [comment]
The issue exist with the china news banner .
1> The Text on Banner is in bold 
2> And the tooltip exist in english , as there there is no tooltip in harman.com for china news

![image](https://cloud.githubusercontent.com/assets/23308564/20832221/0483871e-b8af-11e6-9584-3cf64bc0cafa.png)

**Comment by trupti-dhall** [comment]
baaner issue already mentioned in Issue #81

**Comment by debasis123nandi** [comment]
as banner is a copied of #81 , 
therefore losing the issue
