### ISSUE TITLE
Updated texts are overlapping the download icon

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#83]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: https://wipro48ocphrfau.devcloud.acquia-sites.com/innovation
Step 4 : In device , PC
Step 5: Open in browser,Google Chrome/IE/Mozilla
Step 6 : Edit the text using edit icon
Step 6 : It is observed that updated texts are overlapping the download icon
**Please look into the China site also
Step 7: Screenshot attached

![image](https://cloud.githubusercontent.com/assets/23308564/20752609/24074ba8-b728-11e6-9457-a59077f88f79.png)

**Comment by trupti-dhall** [comment]
Done

**Comment by debasis123nandi** [comment]
Its fine now
