### ISSUE TITLE
Dotted text are not expanding 

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#84]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/innovation
Step 4 : In device PC
Step 5 : Open in browser, Mozilla firefox/IE/Chrome
Step 6 : It is observed that dotted text are not expanding 
**Please check in china site also

Step 7 :
Screenshot attached
![image](https://cloud.githubusercontent.com/assets/23308564/20752867/91bd29aa-b729-11e6-8907-2fc68bc38d51.png)

**Comment by trupti-dhall** [comment]
removed dot dot.provided text restriction as following harman live

**Comment by debasis123nandi** [comment]
Its fine now as discussed with @trupti-dhall
