### ISSUE TITLE
Reset password page is improper

### ISSUE THREAD

**Issue by debasis123nandi** [trupti-dhall/Harman#86]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: https://wipro48ocphrfau.devcloud.acquia-sites.com/user/password
Step 4 : In device PC
Step 5 : Open in browser, Mozilla firefox/IE/Chrome
Step 6 : It is observed that the page is improper
**Please check in china site also

Step 7 :
Screenshot attached

![image](https://cloud.githubusercontent.com/assets/23308564/20828435/9836c83e-b89d-11e6-8bbe-3432c7c4b5c2.png)

**Comment by debasis123nandi** [comment]
In Addition ,

URL : https://wipro48ocphrfau.devcloud.acquia-sites.com/user/register
Page is improper 
![image](https://cloud.githubusercontent.com/assets/23308564/20828630/7a1e8c96-b89e-11e6-9bb5-0c241b879b27.png)


On registering with valid email id , its showing improper page   

![image](https://cloud.githubusercontent.com/assets/23308564/20828603/55d37090-b89e-11e6-880d-105c40254e7f.png)

**Comment by debasis123nandi** [comment]
Still issue exist ::
![image](https://cloud.githubusercontent.com/assets/23308564/20832057/1cef7278-b8ae-11e6-8ffd-30f52b7f4a1c.png)

**Comment by arpita123das** [comment]
Issue resolved
URL:http://wipro48ocphrfau.devcloud.acquia-sites.com/user/register
![acnt](https://cloud.githubusercontent.com/assets/23329067/20834544/051a5952-b8bc-11e6-8cb2-46355ef24714.PNG)

**Comment by debasis123nandi** [comment]
As UI is fine, and discussed with @trupti-dhall  .
Hence closing the issue
