### ISSUE TITLE
Page title is not as per language

### ISSUE THREAD

**Issue by trupti-dhall** [trupti-dhall/Harman#87]
Step 1 : Navigate to the url: http://wipro48ocphrfau.devcloud.acquia-sites.com/user
Step 2 : Login as editor. editor/wipro@123
Step 3 : Navigate to the url: https://wipro48ocphrfau.devcloud.acquia-sites.com/leadership
Step 4 : In device , PC
Step 5: Open in browser,Google Chrome/IE/Mozilla
Step 6 : It is observed that title of English leadership page is in Chinese.

**Comment by debasis123nandi** [comment]
Its fine now
